// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: Sensor.proto

package sensor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorDataPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorValue   float32                `protobuf:"fixed32,1,opt,name=sensor_value,json=sensorValue,proto3" json:"sensor_value,omitempty"`
	SensorType    string                 `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"`
	Id1           string                 `protobuf:"bytes,3,opt,name=id1,proto3" json:"id1,omitempty"`
	Id2           int32                  `protobuf:"varint,4,opt,name=id2,proto3" json:"id2,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorDataPayload) Reset() {
	*x = SensorDataPayload{}
	mi := &file_Sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorDataPayload) ProtoMessage() {}

func (x *SensorDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_Sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorDataPayload.ProtoReflect.Descriptor instead.
func (*SensorDataPayload) Descriptor() ([]byte, []int) {
	return file_Sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorDataPayload) GetSensorValue() float32 {
	if x != nil {
		return x.SensorValue
	}
	return 0
}

func (x *SensorDataPayload) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorDataPayload) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *SensorDataPayload) GetId2() int32 {
	if x != nil {
		return x.Id2
	}
	return 0
}

func (x *SensorDataPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SensorDataPayload     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_Sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_Sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_Sensor_proto_rawDescGZIP(), []int{1}
}

func (x *SensorData) GetData() *SensorDataPayload {
	if x != nil {
		return x.Data
	}
	return nil
}

type SensorDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorDataResponse) Reset() {
	*x = SensorDataResponse{}
	mi := &file_Sensor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorDataResponse) ProtoMessage() {}

func (x *SensorDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Sensor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorDataResponse.ProtoReflect.Descriptor instead.
func (*SensorDataResponse) Descriptor() ([]byte, []int) {
	return file_Sensor_proto_rawDescGZIP(), []int{2}
}

func (x *SensorDataResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SensorDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_Sensor_proto protoreflect.FileDescriptor

const file_Sensor_proto_rawDesc = "" +
	"\n" +
	"\fSensor.proto\x12\x06sensor\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x01\n" +
	"\x11SensorDataPayload\x12!\n" +
	"\fsensor_value\x18\x01 \x01(\x02R\vsensorValue\x12\x1f\n" +
	"\vsensor_type\x18\x02 \x01(\tR\n" +
	"sensorType\x12\x10\n" +
	"\x03id1\x18\x03 \x01(\tR\x03id1\x12\x10\n" +
	"\x03id2\x18\x04 \x01(\x05R\x03id2\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\";\n" +
	"\n" +
	"SensorData\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.sensor.SensorDataPayloadR\x04data\"F\n" +
	"\x12SensorDataResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2S\n" +
	"\rSensorService\x12B\n" +
	"\x0eSendSensorData\x12\x12.sensor.SensorData\x1a\x1a.sensor.SensorDataResponse(\x01B\vZ\t./;sensorb\x06proto3"

var (
	file_Sensor_proto_rawDescOnce sync.Once
	file_Sensor_proto_rawDescData []byte
)

func file_Sensor_proto_rawDescGZIP() []byte {
	file_Sensor_proto_rawDescOnce.Do(func() {
		file_Sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Sensor_proto_rawDesc), len(file_Sensor_proto_rawDesc)))
	})
	return file_Sensor_proto_rawDescData
}

var file_Sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Sensor_proto_goTypes = []any{
	(*SensorDataPayload)(nil),     // 0: sensor.SensorDataPayload
	(*SensorData)(nil),            // 1: sensor.SensorData
	(*SensorDataResponse)(nil),    // 2: sensor.SensorDataResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_Sensor_proto_depIdxs = []int32{
	3, // 0: sensor.SensorDataPayload.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: sensor.SensorData.data:type_name -> sensor.SensorDataPayload
	1, // 2: sensor.SensorService.SendSensorData:input_type -> sensor.SensorData
	2, // 3: sensor.SensorService.SendSensorData:output_type -> sensor.SensorDataResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Sensor_proto_init() }
func file_Sensor_proto_init() {
	if File_Sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Sensor_proto_rawDesc), len(file_Sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Sensor_proto_goTypes,
		DependencyIndexes: file_Sensor_proto_depIdxs,
		MessageInfos:      file_Sensor_proto_msgTypes,
	}.Build()
	File_Sensor_proto = out.File
	file_Sensor_proto_goTypes = nil
	file_Sensor_proto_depIdxs = nil
}
